# Nixpacks configuration for Django
providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt", "python manage.py collectstatic --no-input"]

[start]
cmd = "gunicorn backend.wsgi:application --log-file -"
