# Optimized Nixpacks configuration for Django
providers = ["python"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "python3 manage.py collectstatic --no-input"]

[start]
cmd = "gunicorn backend.wsgi:application --log-file -"
